#!/bin/bash

while [ $# -gt 0 ]; do
  arg=$1
  case $arg in
    shortlist)
      docker ps --format "{{.Names}}" #| sed -e 'N;N;N;s/\n/ /g'
    ;;
    *)
      docker exec -it $arg  /bin/bash -c "export COLUMNS=`tput cols`; export LINES=`tput lines`; exec bash"
    ;;
  esac
  shift
done
